spring.application.name=pedidos

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/florinda_pedidos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Opcional: dê um nome para a conexão ajudar a identificar no painel
spring.rabbitmq.connection-name=${spring.application.name}
server.error.include-stacktrace=never
server.error.include-message=always

