spring.application.name=notas-fiscais

server.port=8082
pedido.api.base-url=http://localhost:8080
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.prefetch=1

# Opcional: dê um nome para a conexão ajudar a identificar no painel
spring.rabbitmq.connection-name=${spring.application.name}